### ISSUE TITLE
[RFC] Personal notes #nobacksDiary

### ISSUE THREAD

**Issue by matthiasnoback** [elcodi/elcodi#339]
- Dependencies on Doctrine common: can be okay, but have to be consequent (no `Doctrine\ORM\...` things).
- Repositories should be defined as interfaces in the component folders, then there should be a Doctrine ORM "adapter" which provides instances of those.
- Mapping shouldn't necessarily be in bundles themselves. You could have a Doctrine ORM "adapter" for those too.
- Events might be implemented using custom event objects and your own event dispatcher (see my blog post about this). Or you may just embrace the Symfony event dispatcher, but you might provide your own instance.
- Some uses of abstract for code reuse
- Analysis of dependencies between components?

Some questions:

- Does it make sense to have all this separation at the bundle level too?

Bundle design:
- No class parameters
- Separation of service files by feature, not by type of things
- Conventions followed, but need not be (`DataFixtures` make sense in non-Symfony applications too

Model design:
- Lots of setters/getters
- Empty object creation using factories (are there no required values?)
- No consistency checks?

**Comment by cordoval** [comment]
I personally think the separation of things as being a smell. Elcodi can or cannot be used as bundles but that does not mean the bundle has to occupy its own top folder. Imo it should just be a hidden folder inside the component. See broadway as an example. Also the classes that we considered as `pure` into the component but that were tainted by symfony namespaces should just be on its infrastructure folder. This approach will actually take care of a lot of boilerplate 2X since we will be removing a lot of duplicated things.

Another observation is the tests. They are not clear if you are not familiar with the testing classes underneath. Some test even things that have little value. I would remove tests and rewrite only tests that are valuable.

The adapter thing is a valuable advice provided we support another gateway but if we are not then it is not a very good idea. We should show this by implementing mongodb or redis repositories if need be.

**Comment by cordoval** [comment]
@matthiasnoback after having dwelling on elcodi a bit, i now get your comment of grouping by feature and not by type. Unfortunately (not in the wrong sense by any means) elcodi is more like a boilerplate layer to easy the building of the proper ecommerce domain/glue logic. Its main feature is to be overridable in the sense of architecture fundamentals, mapping, factories, directors, et al. In that way it is another fresh approach different than sylius. Elcodi is clearer and more explicit and less magic or blur, though it has some parts that are perhaps blur or it is because I still don't understand them well.

One thing that is very magic are the tests, very much on the expectations of testing a bundle which is not the point of unit tests imo.

Elcodi platform is anemic in the sense of the pattern to start, but i believe could be made flexible enough to taylor the objects (overridden now) to embed business logic. Definitely as a read model this could cut it, but not as the domain model yet.

Some comments just to get this thread going. Waiting for your intervention @matthiasnoback "Because ..." :+1: :older_man:
