### ISSUE TITLE
README skeleton for Components and Bundles

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#648]
Definition of README skeleton for Bundles and Components

**Comment by cordoval** [comment]
imo README should be done very minimal, nothing lengthy and go straight to the usage example almost. I have gone away from that spectrum and seen once and again README's placed and not well maintained. 1 README usage is enough and since they will share a lot of boilerplate, let's keep it very DRY please.

**Comment by xphere** [comment]
Closing this in favor of [elcodi/docs](//github.com/elcodi/docs)
