### ISSUE TITLE
Place BambooBundle to Bamboo repository

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#650]
This bundle has no sense to be placed in elcodi.

* Place it to Bamboo repository
* Fix the gitsplit definition

**Comment by cordoval** [comment]
do you want me to send a PR to a repo for bamboo? is there already a new repo? cc @mmoreram

**Comment by xphere** [comment]
This needs work to be done in both repos, `elcodi/elcodi` and `elcodi/bamboo`.

`BambooBundle` existed in `elcodi/elcodi` because tests had a dependency on it, but that's not true anymore, so this makes more sense now in `elcodi/bamboo`.

Also, `.gitsplit.yml` files should be updated in both projects.

**Comment by mmoreram** [comment]
BambooBundle has no sense anymore.

Tomorrow I will place the configuration inside the Bamboo project and I will accept all related PRs :)
