### ISSUE TITLE
[RFC] Release plan

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#657]
IMO we need to define a workflow for releases, both from Elcodi and Bamboo.
This processes must be defined and mostly automated with tools.

- update current version (major, minor, patch, meta)
- add new tag
- update `composer.lock`
- create static files from dynamic ones (template preview comes to mind)

I'd advocate for an adapted `gitflow`, with a `1.0` branch always pointing to the last version, with tags for `v1.0`, `v1.1` and so on, and release branches, like `release-v1.1`, going from `master` to `1.0`, where all this automated processes should be done.

**Comment by javiereguiluz** [comment]
I'll leave here a quick idea in case it's useful. How about digitally signing releases and publishing those signatures automatically in a public repository. It's a widespread practice among professional projects and it's yet another argument to prove that you care about security (I guess that's important for the type of customer you are targeting with Elcodi platform).

It doesn't matter if you don't enforce or use or even publicize those signatures at first. But if in the future you decide to do it, it's better to start signing things since day one. Symfony is one example of those projects signing software since the very beginning (https://github.com/sensiolabs/checksums/blob/master/symfony/browser-kit/v2.0.24.txt). Those signatures were published not so long ago and even today we don't actively use them. But in the near term, we could use them for example in the new installer.

**Comment by xphere** [comment]
Thanks, nice idea! It could make sense for checking the correctness and verify the source of the download. Maybe another repository, with a single `pgp.sig` file, versioned for every tag in `elcodi/elcodi` and pushed automatically in the release process.

**Comment by mmoreram** [comment]
Thanks @javiereguiluz. I will start signing my commits as well, in all projects, and all tags in my projects as well.

It is interesting :)

**Comment by rogergros** [comment]
I agree, we should define a workflow and start working with it. I like the idea of the branches for new releases :)

**Comment by cordoval** [comment]
:+1:

do we want to maintain release branches though? like symfony? wouldn't that be too much? i think tagging and stuff is good but release branches will pose another unnecessary burden perhaps?

**Comment by xphere** [comment]
Once the branch release is merged and tagged, we should usually discard them. But maybe there's a point to have major branches so we can add security bugfixes later. That's something we need to discuss yet.

**Comment by cordoval** [comment]
i think having a short maintenance cycle means you don't patch forever release branches e.g. https://github.com/WordPress/WordPress/tree/3.3-branch . We sit on top of a framework also so this means our cycle must be shorter than the longest underneath. Again I am :-1: on release branches. If discarding is immediate then i am :+1: but i am good if this votes up the for release branches, just would suggest to allow PRs on master like doctrine rather than on 2.3 like in symfony.

**Comment by xphere** [comment]
That's a good point. Since our release cycle is tied to Symfony's, our releases can be throwaway branches, discarded just after the merge and tag. PRs should be made to master, IMO.

**Comment by cordoval** [comment]
great about PRs. Regarding throwaway branches, is the same of just having 1 (aka master) and tagging.

**Comment by xphere** [comment]
The difference is when we start a `release` branch, there's a feature freeze.

To bring this release to a stable state, could take from a few hours to a week, only receiving minor corrections, bugs and security fixes, besides specific actions that should take in each release (upgrading versions, generating statics…)

But new features will go to master, and not merging onto the release branch. That's why I want a full definition of the process and a document describing it.

**Comment by cordoval** [comment]
i understand now thx

**Comment by xphere** [comment]
Can we have some discussion about this before the D-day, please? /ping @elcodi/owners
