### ISSUE TITLE
[PRODUCT] Subscription Based Products

### ISSUE THREAD

**Issue by patrick-mcdougle** [elcodi/elcodi#784]
I'm considering using elcodi for a project in the near future. One of our needs is a subscription based product. A customer is able to sign up (pre-pay) for 1-month, 3-months, or 6-months and we ship a product to them once per month. After that we auto-renew them and bill them. I see the billing / issuing as some sort of script (probably a console command) that gets all the subscribers and checks if we owe them a product, if we do, we create an order, but don't bill them, and if they owe us, create an order for them and bill them. Does anyone else have any thoughts about how to go about this? I'd likely take the lead on writing a good chunk of this, but I'd love to hear community input for ways to design it flexibly and outside of only my use case. Thoughts?

**Comment by mmoreram** [comment]
@patrick-mcdougle Hi!

I was reviewing all the issues here, and I saw yours... right now :(
Sorry about that, and thanks for opening it.

About your proposal... this seems a very specific case, and I cannot see how useful it could be by adding this feature in the core. Anyway, this is the great example about a Plugin.
Since your Issue, we've been working so hard for creating a good base about how a Plugin should be done, so you should find enough information and documentation [here](http://elcodi.io/docs/book/plugins/) - Of course, if you're still interested in the platform :)

Please, any help, ask it in our [gitter channel](http://gitter.im/elcodi/elcodi)

Thanks :)
