### ISSUE TITLE
Fixtures cache

### ISSUE THREAD

**Issue by octante** [elcodi/elcodi#857]
Hi!

The command that loads fixtures    "Elcodi\Bundle\FixturesBoosterBundle\Command\LoadDataFixturesDoctrineCommand" is caching the database file. We have a problem with this, because the unique condition is the path of fixtures, if we change a fixture content system is not able to see this change and file is loaded from cache.

I propose to include another condition to avoid this error. Not to remove it, so is a great improvement to run behat tests :)

**Comment by mmoreram** [comment]
Well, this feature is created for tests boosting, so it should be as faster as possible. Once the tests are run, you should not expect that your fixtures are going to change, so you will not have this problem.

Then, to avoid this situation (not issue nor problem), what I recommend you is removing all `/tmp/Elcodi/*` or `/tmp/Bamboo/*` data in order to create new fresh fixtures, even if they are the same.
